### ISSUE TITLE
为什么会安装失败呢

### ISSUE THREAD

**Issue by SuperZhangJian** [hyj1991/v8-profiler-node8#10]
本来安装easy-monitor的，结果也提示同样的错误

`> v8-profiler-node8@6.1.1 preinstall /www/wwwroot/xinger-client/node_modules/v8-profiler-node8
> node -e 'process.exit(0)'

> v8-profiler-node8@6.1.1 install /www/wwwroot/xinger-client/node_modules/v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for v8-profiler-node8@6.1.1 and node@12.14.1 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/www/wwwroot/xinger-client/node_modules/v8-profiler-node8/build/profiler/v6.1.1/node-v72-linux-x64' 
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 3.10.0-1062.el7.x86_64
gyp ERR! command "/www/node/bin/node" "/www/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /www/wwwroot/xinger-client/node_modules/v8-profiler-node8
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/www/node/bin/node /www/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/www/wwwroot/xinger-client/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 3.10.0-1062.el7.x86_64
node-pre-gyp ERR! command "/www/node/bin/node" "/www/wwwroot/xinger-client/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /www/wwwroot/xinger-client/node_modules/v8-profiler-node8
node-pre-gyp ERR! node -v v12.14.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/www/node/bin/node /www/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
npm WARN babel-plugin-transform-vue-jsx@3.7.0 requires a peer of babel-helper-vue-jsx-merge-props@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN xinger-client@1.0.0 No repository field.
npm WARN xinger-client@1.0.0 scripts['server'] should probably be scripts['start'].
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@6.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler-node8@6.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-21T14_39_49_664Z-debug.log`

这是在centos7下的，在windows下安装都没问题，node版本都是12.14.1

**Comment by hyj1991** [comment]
> gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build

看第一条错误，显然是没权限删除 build 目录

**Comment by SuperZhangJian** [comment]
好吧，但是我改了node版本也解决了

**Comment by hyj1991** [comment]
可以了就行
