### ISSUE TITLE
Command exited with code -1073741819 (node-v14.4.0)

### ISSUE THREAD

**Issue by hyj1991** [hyj1991/v8-profiler-node8#18]
![image](https://user-images.githubusercontent.com/19908330/86771770-6374be00-c085-11ea-84a2-b46d274ee42e.png)

Can't figure out how this error occurred and can't reproduce it on windows with node-v14.4.0 :(

**Comment by hyj1991** [comment]
~~Ref: https://ci.appveyor.com/project/hyj1991/v8-profiler-node8/builds/33952795/job/c33mi1dqt8wlonu5~~

Ref: https://ci.appveyor.com/project/hyj1991/v8-profiler-node8/build/job/4r4t3002v77jueiq

**Comment by Widdershin** [comment]
I can't see the build log (Build not found or access denied.), did this happen during compilation or at runtime?

I've been working on getting Node instrumented with AFL for fuzzing so hopefully we can track down any remaining issues.

**Comment by hyj1991** [comment]
> I can't see the build log (Build not found or access denied.), did this happen during compilation or at runtime?

It seems happing during runtime, but sometimes it appears when executing `npm version`.

You can restart the [CI#v8-profiler-node8](https://ci.appveyor.com/project/hyj1991/v8-profiler-node8), it seems that only v14.x will be errored with exit code -1073741819  (not every time).

**Comment by Widdershin** [comment]
Can we add the [segfault-handler](https://github.com/ddopson/node-segfault-handler/) library to try and catch the output?

**Comment by hyj1991** [comment]
> Can we add the [segfault-handler](https://github.com/ddopson/node-segfault-handler/) library to try and catch the output?

Good idea, let me try

**Comment by Widdershin** [comment]
I made a PR #19 to try and pinpoint it.

On my first run the error occured on `npm install`, which makes me wonder if it's actually an issue with Appveyor or the build cache? Since none of our code should actually get loaded at that point right?

**Comment by hyj1991** [comment]
landed in 9ce5023.
