### ISSUE TITLE
ERROR (404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz 

### ISSUE THREAD

**Issue by albesdev** [hyj1991/v8-profiler-node8#2]
Get this error: 

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@10.4.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@10.4.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)

**Comment by hyj1991** [comment]
this is not an error, node pre gyp failed will fallback to native compile

**Comment by albesdev** [comment]
ok any kind of advice to fix it?

**Comment by albesdev** [comment]
thank you

**Comment by hyj1991** [comment]
normally you can still install success by native compile (npm rebuild)

**Comment by albesdev** [comment]
same error executing npm install v8-profiler-node8 -g

npm 6.1.0
node v10.4.0
nvm 0.25.4

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@10.4.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@10.4.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)

**Comment by hyj1991** [comment]
is there any other error?
> falling back to source compile with node-gyp

i saw this

**Comment by albesdev** [comment]
a lot of errors, this is the complete log: 

npm i npm@latest -g
/Users/albe/.nvm/versions/node/v10.4.0/bin/npm -> /Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/npm/bin/npm-cli.js
/Users/albe/.nvm/versions/node/v10.4.0/bin/npx -> /Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.1.0
added 546 packages from 157 contributors, removed 278 packages and updated 4 packages in 15.121s
Jesse:noaudit_backend albe$ npm install v8-profiler-node8 -g

> v8-profiler-node8@5.7.8 preinstall /Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8
> node -e 'process.exit(0)'


> v8-profiler-node8@5.7.8 install /Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@10.4.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@10.4.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/profiler/src/profiler.o
  CXX(target) Release/obj.target/profiler/src/profiler.o
  CXX(target) Release/obj.target/profiler/src/cpu_profiler.o
sed: ./Release/.deps/Release/obj.target/profiler/src/profiler.o.d.raw: No such file or directory
rm: ./Release/.deps/Release/obj.target/profiler/src/profiler.o.d.raw: No such file or directory
make: *** [Release/obj.target/profiler/src/profiler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/Users/albe/.nvm/versions/node/v10.4.0/bin/node" "/Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64"
gyp ERR! cwd /Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8
gyp ERR! node -v v10.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/albe/.nvm/versions/node/v10.4.0/bin/node /Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.6.0
node-pre-gyp ERR! command "/Users/albe/.nvm/versions/node/v10.4.0/bin/node" "/Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8
node-pre-gyp ERR! node -v v10.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/Users/albe/.nvm/versions/node/v10.4.0/bin/node /Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@5.7.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler-node8@5.7.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/albe/.npm/_logs/2018-06-12T15_32_34_426Z-debug.log
Jesse:noaudit_backend albe$ In file included from ../src/cpu_profiler.cc:1:
../src/cpu_profiler.h:6:10: fatal error: 'nan.h' file not found
#include "nan.h"
         ^~~~~~~
1 error generated.
make: *** [Release/obj.target/profiler/src/cpu_profiler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/Users/albe/.nvm/versions/node/v10.4.0/bin/node" "/Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64"
gyp ERR! cwd /Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8
gyp ERR! node -v v10.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-gyp[14592]: ../src/node.cc:4012:void node::PlatformExit(): Assertion `(err) != (-1)' failed.
 1: node::Abort() [/Users/albe/.nvm/versions/node/v10.4.0/bin/node]
 2: node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/Users/albe/.nvm/versions/node/v10.4.0/bin/node]
 3: node::PlatformExit() [/Users/albe/.nvm/versions/node/v10.4.0/bin/node]
 4: __cxa_finalize_ranges [/usr/lib/system/libsystem_c.dylib]
 5: exit [/usr/lib/system/libsystem_c.dylib]
 6: node::Abort(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/albe/.nvm/versions/node/v10.4.0/bin/node]
 7: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/Users/albe/.nvm/versions/node/v10.4.0/bin/node]
 8: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/albe/.nvm/versions/node/v10.4.0/bin/node]
 9: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/albe/.nvm/versions/node/v10.4.0/bin/node]
10: 0x95faac841bd
11: 0x95faac93429
12: 0x95faac93429

**Comment by hyj1991** [comment]
that seems node-gyp building error with node-v10.4.0, i'll try and fix this version tomorrow
i'm sure it works with node-v10.1.0 before
thanks for report this bug

**Comment by albesdev** [comment]
That's great! Thanks for your support

**Comment by hyj1991** [comment]
@albes fixed this bug
try `npm i v8-profiler-node8` again

**Comment by albesdev** [comment]
That's great! It is working. 
Another question: 

how can I set the path? I was looking that it is searching for the v8 profiler in a lot of paths

0|API      | 2018-06-13T09:27:07.397Z axm:profiling [-] v8-profiler not found in path /Users/albe/node_modules/v8-profiler
0|API      | 2018-06-13T09:27:07.397Z axm:profiling Checking v8-profiler in path /Users/node_modules/v8-profiler
0|API      | 2018-06-13T09:27:07.399Z axm:profiling [-] v8-profiler not found in path /Users/node_modules/v8-profiler
0|API      | 2018-06-13T09:27:07.399Z axm:profiling Checking v8-profiler in path /node_modules/v8-profiler
0|API      | 2018-06-13T09:27:07.399Z axm:profiling [-] v8-profiler not found in path /node_modules/v8-profiler
0|API      | 2018-06-13T09:27:07.399Z axm:profiling [x] v8-profiler NOT FOUND
0|API      | 2018-06-13T09:27:07.399Z axm:profiling Checking v8-profiler-node8 in path /Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/pm2/lib/node_modules/v8-profiler-node8
0|API      | 2018-06-13T09:27:07.400Z axm:profiling [-] v8-profiler-node8 not found in path /Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/pm2/lib/node_modules/v8-profiler-node8
0|API      | 2018-06-13T09:27:07.400Z axm:profiling Checking v8-profiler-node8 in path /Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/pm2/node_modules/v8-profiler-node8
0|API      | 2018-06-13T09:27:07.400Z axm:profiling [-] v8-profiler-node8 not found in path /Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/pm2/node_modules/v8-profiler-node8
0|API      | 2018-06-13T09:27:07.400Z axm:profiling Checking v8-profiler-node8 in path /Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8
0|API      | 2018-06-13T09:27:07.400Z axm:profiling [+] v8-profiler-node8 detected in path /Users/albe/.nvm/versions/node/v10.4.0/lib/node_modules/v8-profiler-node8
0|API      | 2018-06-13T09:27:07.402Z axm:profiling v8-profiler sucessfully enabled

**Comment by hyj1991** [comment]
`npm install some-module` without **-g** flag will first installed at the **current directory/node_modules/v8-profiler-node8**

I guess you installed with **-g**

**Comment by albesdev** [comment]
Is it possible to have the version for node@8.11.3 on amazonaws?

**Comment by hyj1991** [comment]
sorry, I'm not familiar with amazonaws. In China, We usually use Alibaba Cloud Computing.

**Comment by albesdev** [comment]
Sorry, I mean with node v8.11.3 I get  v8-profiler-node8 NOT FOUND.
error:
node-pre-gyp WARN Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-darwin-x64.tar.gz

**Comment by hyj1991** [comment]
this is normal beacuse there is no compiled file in the server

usually, node-pre-gyp will try to download compiled file from the server according to it's own **NODE_MODULE_VERSION** which in [src/node_version.h](https://github.com/nodejs/node/blob/master/src/node_version.h#L114), then if download failed, npm will fallback to native compile (use node-gyp), so this is not an error, just a warning

v8-profiler-node8 is based on [v8-profiler](https://github.com/node-inspector/v8-profiler), and sadily the official team of v8-profiler no longer maintained this project, so no one to put the compiled binary  onto the server

I create this project also because they don't maintain v8-profiler anymore
