### ISSUE TITLE
Coredumped with snapshot

### ISSUE THREAD

**Issue by hyj1991** [hyj1991/v8-profiler-node8#22]
Ref: https://travis-ci.org/github/hyj1991/v8-profiler-node8/jobs/708001801

Maybe we should add `segfault-handler` for the test suit again.

**Comment by Widdershin** [comment]
Strange that it was on Node 4, I'll see if I can figure it out.

**Comment by Widdershin** [comment]
Hmmm I wasn't able to reproduce locally, segfault-handler seems like a good idea.
