### ISSUE TITLE
Controlling CpuProfilingLoggingMode

### ISSUE THREAD

**Issue by Widdershin** [hyj1991/v8-profiler-node8#24]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/398365/90212148-b0973d00-de46-11ea-958f-b7eabdbd28c6.png">

Hiya.

With Node 12+ we can control extra options for `CpuProfiler::New`. I need to be able to control `CpuProfilingLoggingMode` for my project, because the default `kLazyLogging` causes a 250ms+ delay when starting a profile if not profiles are running.

I am willing to make a PR if you are interested, but I am not sure what the best API is:

 1) Add a profiler constructor - `require('v8-profiler-node8').makeProfiler({eagerLogging: true}).startProfiling('test')`
 2) Environment variables - `cpu_profiler.cc` uses `std::getenv` to control `CpuProfiler::New` options
 3) `require('v8-profiler-node8').setProfilerOptions({eagerLogging: true})` and then only initialize profiler when it's used

1 seems probably best, and we could do that while keeping the existing interface intact.

2 feels a little hacky, but is probably the easiest

3 just feels wrong, what if it changes midway?

Let me know what you think. I can also just maintain a fork if that's easier but would prefer to keep contributing.

**Comment by hyj1991** [comment]
Landed in `v8-profiler-node8@v7.1.1` with `next` tag.
