### ISSUE TITLE
The CPU usage is doubled if I enable the profiler

### ISSUE THREAD

**Issue by ashokduraik** [hyj1991/v8-profiler-node8#29]
The CPU usage is doubled if I enable the profiler.
For example if the CPU usage is 10%, after I enable the profiler it became 20%.
I attached the cpuprofile file with this. Please try to improve the performance 

[Simple_node_app_8081_8081_19_04_2021_15_43.zip](https://github.com/hyj1991/v8-profiler-node8/files/6335173/Simple_node_app_8081_8081_19_04_2021_15_43.zip)

**Comment by hyj1991** [comment]
Starting the v8 cpu profiler needs additional resources, so that is normal.

`CPU profiling` just calling the v8 function: 
https://github.com/hyj1991/v8-profiler-node8/blob/master/src/cpu_profiler.cc#L59

> Please try to improve the performance

So unfortunately, the performance improvement can only wait for the upstream :(
