### ISSUE TITLE
6.4.0 binaries

### ISSUE THREAD

**Issue by Widdershin** [hyj1991/v8-profiler-node8#39]
Hi!

Did the binary publishing action break? I'm happy to fix it if desired to generate 6.4.0 binaries.

I think Github supports retrying individual failed jobs now if that was the issue.

Thanks,
Nick

**Comment by hyj1991** [comment]
Hello, the v6.x version of `v8-profiler-node8` is completely based on `v8-profiler-next` which provides pre-compiled binaries now.

**Comment by hyj1991** [comment]
See https://github.com/hyj1991/v8-profiler-node8/blob/master/v8-profiler.js

**Comment by Widdershin** [comment]
Okay great, thanks for that!

**Comment by hyj1991** [comment]
Actually `v8-profiler-next` supports `worker_threads` & `node-pre-gyp` now:

* [feat: can be used in worker threads](https://github.com/hyj1991/v8-profiler-next/commit/8eea60851be85e444cf933f838eba5c7a7bcfc70)
* [feat: support node-pre-gyp](https://github.com/hyj1991/v8-profiler-next/commit/1b91cce5bc17f46ebb58ecaf512cbbdab37122cc)

Any more:
* [fix: improve performance by tuning profiler disposal](https://github.com/hyj1991/v8-profiler-next/commit/9d213ed723a26f0de2f29a780b58b2fd48265165)
* [feat: support cpuprofiling logging mode](https://github.com/hyj1991/v8-profiler-next/commit/a3bd8173c6318d28fd7c78563aabb5ff7d3652e7)

**Comment by hyj1991** [comment]
As these may be we can make v8-`profiler-node8@v7.x` also based on `v8-profiler-next` :)

**Comment by hyj1991** [comment]
Hello, I have released `v8-profiler-next@7.4.0` with the `next` tag, which is completely based on `v8-profiler-next@1.9.0+`, please let me know if there are any problems :)

Reference: https://github.com/hyj1991/v8-profiler-node8/tree/v7.4.0
