### ISSUE TITLE
最新版本执行得到的cpuprofile使用浏览器的javacript性能剖析器看到的时间都是0

### ISSUE THREAD

**Issue by linguitang** [hyj1991/v8-profiler-node8#41]
![image](https://user-images.githubusercontent.com/8371546/172039598-6d59f38c-1980-4da2-aa70-8d53085b53a2.png)

profiler.startProfiling('1', true);
var profile1 = profiler.stopProfiling();

profile1.export(function(error, result) {
  fs.writeFileSync('profile1.cpuprofile', result);
  profile1.delete();
});
这种用法有问题吗？

**Comment by linguitang** [comment]
使用这个 https://www.speedscope.app/ 就可以看了

**Comment by hyj1991** [comment]
@linguitang 将生成的 cpuprofile 贴出来，我看下

**Comment by linguitang** [comment]
我发你gmail了 @hyj1991

**Comment by hyj1991** [comment]
好的，我看下

**Comment by hyj1991** [comment]
这个不是 Bug，在早期的 Chrome devtools 实现中，旧的 cpuprofile 序列化格式中的 `startTime`  和 `endTime` 精度是秒，这样对于

```js
profiler.startProfiling('1', true);
var profile1 = profiler.stopProfiling();

profile1.export(function(error, result) {
fs.writeFileSync('profile1.cpuprofile', result);
profile1.delete();
});
```

这种生成的 cpuprofile 它的采样耗时在 1s 内就结束了，因此其 `startTime` 和 `endTime` 是一样的，而具体的 `samples` 数组记录依旧是精确到纳秒的，这样才会出现你的这个 `NaN` 的现象。

`v8-profiler-node8` 这个库默认的 cpuprofile 序列化格式考虑到兼容性遵循了旧的 Chrome devtools 实现。

实际上 Chrome devtools 已经采用了新的 cpuprofile 序列化格式，会将 `startTime` 和 `endTime`  的精度更改为纳秒，可以解决你的这个问题，同样 `v8-profiler-node8` 也支持，只需要在采样前配置下 generate type 即可：

```js
// 默认是 0，表示用旧的序列化格式，设置为 1 表示新的序列化格式
profiler.setGenerateType(1);
```

**Comment by linguitang** [comment]
没问题了，谢谢
