### ISSUE TITLE
Cannot find module './build/profiler/v6.0.1/node-v47-darwin-x64/profiler.node'

### ISSUE THREAD

**Issue by shijiebei2014** [hyj1991/v8-profiler-node8#6]
I run the code and the v8-profiler-node8 run error. I saw only the ./build/profiler/v6.0.1/node-v57-darwin-x64/profiler.node and not found the node-v47-darwin-x64. How can I solve this problem?

**Comment by hyj1991** [comment]
Any other error info? It'll fall back to local compile when this error occurred.

**Comment by shijiebei2014** [comment]
Thank you. I know the reason.The node version  was inconsistent

**Comment by larry-dalmeida** [comment]
@shijiebei2014 can you please further explain the issue and the fix you applied? I am facing the same one but not sure if I need to go back to an older version of node.

My setup:
- Node `v12.18.2`
- NPM `6.14.5`
- v8-profiler-node8 `^6.2.0`

This is what I get in my console:
```
Error: Cannot find module './build/profiler/v6.2.0/node-v72-darwin-x64/profiler.node'
Require stack:
/Users/larry-dalmeida/Desktop/abc/xyz/v8-profiler-node8/v8-profiler.js
```

**Comment by larry-dalmeida** [comment]
@shijiebei2014 Please ignore the comment above - turned out to be an issue with [Mac OS Catalina](https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md)
