### ISSUE TITLE
Module 'v8-profiler-node8' can not install on Windows

### ISSUE THREAD

**Issue by xiaojue** [hyj1991/v8-profiler-node8#7]
https://github.com/daruk-framework/daruk/issues/50

**Comment by xiaojue** [comment]
https://www.luogu.org/paste/llum05p9

**Comment by hyj1991** [comment]
![image](https://user-images.githubusercontent.com/19908330/57748339-22e11500-770c-11e9-9289-61a19bad8ad5.png)

If there is any other question, you can reopen this issue.
