### ISSUE TITLE
Build using v8-profiler-node8 causing issue when installing on windows. 

### ISSUE THREAD

**Issue by gupta-nitish** [hyj1991/v8-profiler-node8#9]
My application created the installer for node services, that installer is build on some server but while i am installing it on windows machine it will create issue in starting node services those are using v8-profiler-node8. While trying to start service it throw following error:

> Error: Cannot find module './build/profiler/v6.1.1/node-v64-win32-ia32/profiler.node'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (C:\Program Files (x86)\NLT\bin\node_modules\v8-profiler-node8\v8-profiler.js:2:15)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at r (C:\Program Files (x86)\NLT\bin\tracking-service.js:1:91)
>     at C:\Program Files (x86)\NLT\bin\tracking-service.js:1:282
>     at Object.51 (C:\Program Files (x86)\NLT\bin\tracking-service.js:6:25685)
>     at r (C:\Program Files (x86)\NLT\bin\tracking-service.js:1:231)

Seems like while installing v8-profiler-node8 on server, it created on some URL, which is not found while installing on windows.

**Comment by hyj1991** [comment]
Execute `npm install v8-profiler-node` on your windows machine, and is there any error message while installing this module?

**Comment by gupta-nitish** [comment]
We are creating install on another machine, where we are executing npm insatll command. It is working fine.
But we are installing the installer on some other machine, where we can't run npm install command.

**Comment by hyj1991** [comment]
`v8-profiler-node8` is a `c++` addon, so we need to compile it (which `npm install` doing) on the machine where we want to run it because of cross-compile.

If just copying the installed node_modules dir to other machines, it won't work as well.
